version: '3.7'

services:
  web:
    build:
      context: .
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  bundle_cache:
  pgdata:
